name: ussd_service
description: A Flutter plugin to make silent USSD requests and read their responses, using Android's sendUssdRequest. iOS is not supported.
version: 1.0.1+2
homepage: https://github.com/bouarmodskip/ussd_mbo.git
documentation: https://github.com/bouarmodskip/ussd_mbo.git
repository: https://github.com/bouarmodskip/ussd_mbo.git
issue_tracker: https://github.com/bouarmodskip/ussd_mbo/issues

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.22.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:

  plugin:
    platforms:
      android:
        package: com.ktminnov.ussd_service
        pluginClass: UssdServicePlugin
